# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jennifer/Documents/CMU Year 5/Fall Semester/18643/ReturnOf447Hype/Lab1/Ultra96_Basic_System/Ultra96_Basic_System.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'design_1_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jennifer/Documents/CMU Year 5/Fall Semester/18643/ReturnOf447Hype/Lab1/Ultra96_Basic_System/Ultra96_Basic_System.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jennifer/Documents/CMU Year 5/Fall Semester/18643/ReturnOf447Hype/Lab1/Ultra96_Basic_System/Ultra96_Basic_System.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Jennifer/Documents/CMU Year 5/Fall Semester/18643/ReturnOf447Hype/Lab1/Ultra96_Basic_System/Ultra96_Basic_System.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'design_1_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jennifer/Documents/CMU Year 5/Fall Semester/18643/ReturnOf447Hype/Lab1/Ultra96_Basic_System/Ultra96_Basic_System.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jennifer/Documents/CMU Year 5/Fall Semester/18643/ReturnOf447Hype/Lab1/Ultra96_Basic_System/Ultra96_Basic_System.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
