/* This file is automatically generated based on your hardware design. */
#include "memory_config.h"

struct memory_range_s memory_ranges[] = {
	{
		"axi_bram_ctrl_0_Mem0",
		"axi_bram_ctrl_0",
		0xA0000000,
		65536,
	},
	{
		"psu_ddr_0_MEM_0",
		"psu_ddr_0",
		0x00000050,
		2146434992,
	},
	/* psu_ocm_ram_0_MEM_0 memory will not be tested since application resides in the same memory */
};

int n_memory_ranges = 2;
